# Redisサーバーの接続情報。パスワード/ユーザー名が不要な場合は、nullと書いてください
redis:
  hostname: "localhost"
  port: 6379
  username: null
  password: null
  ssl: false

# サーバーの識別子。必ず被らないように設定してください
serverIdentifier: "Server1"

# プラグイン起動時に登録するチャンネル名。空にすることも可能です。APIを使用して登録することもできます
# 詳細な情報は、GitHubをご覧ください: https://github.com/ATTSUMAN08/ForestRedisAPI
channels:
  - "my_channel"