name: ForestRedisAPI
main: cz.foresttech.forestredis.spigot.ForestRedisSpigot
author: ForestTech
version: 1.0.2
description: Powerful and simple Redis API by ForestTech
api-version: 1.13

commands:
  forestredis:
