[versions]
shadow = "9.0.0-beta4"

paperApi = "1.18.2-R0.1-SNAPSHOT"
velocityApi = "3.4.0-SNAPSHOT"
bungeeApi = "1.21-R0.1-SNAPSHOT"
jedis = "5.2.0"
gson = "2.11.0"
snakeYaml = "2.3"

[plugins]
shadow =  { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
velocityApi = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocityApi" }
bungeeApi = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungeeApi" }
jedis = { group = "redis.clients", name = "jedis", version.ref = "jedis" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
snakeYaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeYaml" }